### PR TITLE
Added cpp and javascript linter

### PR DESCRIPTION
**Pull request by satoufuyuki**
P, gajawab pki

### CODE REVIEW

**Comment by satoufuyuki** [comment]
MERGEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by dwicao** [comment]
@KurokuTetsuya Can u provide a screenshot about the input and output?
Because I don't really know what this command do

**Comment by satoufuyuki** [comment]
> @KurokuTetsuya Can u provide a screenshot about the input and output?
> Because I don't really know what this command do

image

**Comment by satoufuyuki** [comment]
> > @KurokuTetsuya Can u provide a screenshot about the input and output?
> > Because I don't really know what this command do
> 
> image

# Javascript linter
image

**Comment by satoufuyuki** [comment]
> @KurokuTetsuya Can u provide a screenshot about the input and output?
> Because I don't really know what this command do

# Cpp linter

image

**Comment by dwicao** [comment]
LGTM, thanks for the contribution :)

**Pull request merged**
